[build]
  command="npm run build"
  publish=".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true

[build.environment]
  NEXT_PUBLIC_DATA_FETCHING="ssr"

[template.environment] 
  COMMERCELAYER_CLIENT_ID="mWsav_ySuCsiIXYhpE-PjWKOjfXj4DEvlZQyU1xLBb4"
  COMMERCELAYER_ENDPOINT="https://metrolinx-demo.commercelayer.io"
  COMMERCELAYER_ORGANISATION_SLUG="metrolinx-demo"
  CONTENTSTACK_API_KEY="blte6def82151f0fd5e"
  CONTENTSTACK_DELIVERY_TOKEN="cs39b5e5f22dfa24cd589eed02"
  CONTENTSTACK_ENVIRONMENT="development"
